### ISSUE TITLE
trying to save wrong filename in node.js

### ISSUE THREAD

**Issue by gavinengel** [xreader/inplaceeditor#16]
I noticed that server.js tries to save over a file called "http://localhost:3000/index.html" instead of simply "index.html".  I have to hardcode this to get it to work for me in server.js:

       var name = 'index.html';//req.param('name', null);

**Comment by xreader** [comment]
You have to set SERVER_PATH = 'http://localhost:3000/' in js/inplaceeditor.js to fix this problem
